import os
from pathlib import Path
from uuid import uuid4

import pytest
from flask_migrate import upgrade
from sqlalchemy import create_engine, text

from backend.app import create_app
from backend.app.config import normalize_database_url
from backend.app.extensions import db


MIGRATIONS = str(Path(__file__).resolve().parents[1] / "migrations")
DATABASES = ["sqlite"] + (["mysql"] if os.getenv("MYSQL_TEST_URL") else [])


@pytest.fixture(scope="session")
def mysql_test_url():
    """Create/drop only a unique disposable schema; never use an existing database."""
    url = normalize_database_url(os.environ["MYSQL_TEST_URL"])
    if url.drivername != "mysql+pymysql":
        raise ValueError("MYSQL_TEST_URL must be a MySQL/PyMySQL URL.")
    database_name = "stockflow_test_" + uuid4().hex
    engine = create_engine(url.set(database=None), isolation_level="AUTOCOMMIT")
    with engine.connect() as connection:
        connection.execute(text(
            f"CREATE DATABASE `{database_name}` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci"
        ))
    try:
        yield url.set(database=database_name)
    finally:
        with engine.connect() as connection:
            connection.execute(text(f"DROP DATABASE `{database_name}`"))
        engine.dispose()


@pytest.fixture(params=DATABASES)
def database_app(request):
    url = request.getfixturevalue("mysql_test_url") if request.param == "mysql" else "sqlite:///:memory:"
    app = create_app({"TESTING": True, "SECRET_KEY": "test-secret", "SQLALCHEMY_DATABASE_URI": url})
    with app.app_context():
        upgrade(directory=MIGRATIONS)
        try:
            yield app
        finally:
            db.session.remove()
            if request.param == "mysql":
                # The schema was generated by mysql_test_url for this test run only.
                with db.engine.begin() as connection:
                    for table in reversed(db.metadata.sorted_tables):
                        connection.execute(table.delete())
            db.engine.dispose()
